services:
  - type: web
    name: mathigon-college
    env: node
    plan: free
    nodeVersion: "20"
    buildCommand: npm install && npm run postinstall && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
